project:
  type: book

book:
  title: "Assignment 1"
  author: "Ben Frost"
  date: "02/09/2026"
  sidebar:
    style: floating
    collapse-level: 2
  chapters:
    - index.qmd
    - DayOnePractical.qmd
    - DayThreePractical.qmd
    - DayFourPractical.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  echo: true

